---
title: "DACSS_690VHW2_Code"
author: "Felix Ramirez Mota"
date: "2026-03-10"
output: html_document
---
# Packeges 
```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(scales)
```

## Looking Into Data

```{r}
getwd()

mass_ed_df<-read.csv("/Users/felixramirez/Desktop/DACSS 690V/DACSS_690VHW2/MASSdata.csv")

dim(mass_ed_df)
names(mass_ed_df)
str(mass_ed_df,width = 70,strict.width='cut')
```

## Changing Varible Classes

```{r}
grades <- c("PK","KK","KG", "01","02","03","04", "05", "06", "07", "08", "09", "10", "11", "12", "UG")

mass_ed_df<-mass_ed_df |>
  mutate(
NCES.School.ID = as.character(NCES.School.ID),
NCES.District.ID = as.character(NCES.District.ID),
ZIP = as.character(ZIP),
ZIP.4.digit = as.character(ZIP.4.digit),
Locale.Code = as.factor(Locale.Code),
Locale = as.factor(Locale),
Charter = as.factor(Charter),
Students = as.numeric(Students),
Teachers = as.numeric(Teachers),
Student.Teacher.Ratio = as.numeric(Student.Teacher.Ratio),
Low.Grade = factor(Low.Grade, levels = grades, ordered = TRUE),
High.Grade =factor(High.Grade, levels = grades, ordered = TRUE),
Free.Lunch = as.numeric(Free.Lunch),
Reduced.Lunch = as.numeric(Reduced.Lunch)
)

str(mass_ed_df)
table(unlist(sapply(mass_ed_df, class)))
```

# Creating New Varible

```{r}
head(mass_ed_df$Locale,20)

mass_ed_df<-mass_ed_df|>
  mutate(
    Locale2 = case_when(
      grepl("City", Locale) ~"City",
      grepl("Suburb", Locale) ~"Suburb",
      grepl("Town", Locale) ~"Town",
      grepl("Rural", Locale) ~"Rural"
    )
  )
head(mass_ed_df$Locale2,20)
```
# Tables for Categorical Plot

```{r}
LocaleTable=table(mass_ed_df$Locale2,
                 useNA = "ifany") 
LocaleTable_freq <- as.data.frame(LocaleTable)
names(LocaleTable_freq) <- c("Locale", "Count")
LocaleTable_freq$Percent <- prop.table(LocaleTable) *100

LocaleTable_freq

```

# Visualizations

```{r}
schoolloc_plot<-ggplot(LocaleTable_freq, aes(x = reorder(Locale, Percent), y=Percent, fill = Locale))+
  geom_col()+
  labs(
    title = "Where are Public Schools located in MA?",
    subtitle = "Location Type of Massachussetts Public Schools",
    x = NULL,
    y = NULL,
    caption = "Source: U.S Department of Education "
  )+
  geom_hline(
    yintercept = 25,
    linetype = "dashed",
    linewidth = 1.5,
    alpha = 0.5
  )+
  scale_y_continuous(breaks = c(0,20,40,60,80),
                     limits = c(0,80),
                     labels = unit_format(suffix='%'))+
  theme_classic()+
  scale_fill_brewer(palette = "Set2")+
  theme(plot.caption = element_text(hjust = 0),
        plot.subtitle = element_text(hjust = 0.5),
        plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text = element_text(face = "bold", size = 12),
        axis.line = element_line(linewidth = 1)
        )+
  geom_text(vjust= 0,
            size = 5,
            aes(y= Percent,
                label = paste0(round(Percent,2), '%'))
  )
schoolloc_plot

saveRDS(schoolloc_plot, "schoolloc_plot.rds")
  
```
# Numerical Plot

```{r}
summary(mass_ed_df$Student.Teacher.Ratio)

mass_ed_df_forplot <- mass_ed_df|>
  filter(!is.na(Student.Teacher.Ratio))
boxratio <-ggplot(mass_ed_df_forplot, aes(x=Student.Teacher.Ratio))+
  theme_classic()+
  geom_boxplot()

upperT<-ggplot_build(boxratio)$data[[1]]$xmax
lowerT<-ggplot_build(boxratio)$data[[1]]$xmin
low0count <- sum(ggplot_build(boxratio)$data[[1]]$outliers[[1]]<= lowerT)
upper0count <- sum(ggplot_build(boxratio)$data[[1]]$outliers[[1]]>= upperT)
md=median(mass_ed_df_forplot$Student.Teacher.Ratio,na.rm = TRUE)
mn=mean(mass_ed_df_forplot$Student.Teacher.Ratio,na.rm = TRUE)

upperT
lowerT
low0count
upper0count
md
mn

```

```{r}
sdt_tchrat_school<-ggplot(mass_ed_df_forplot, aes(x=0,y=Student.Teacher.Ratio))+
  theme_classic()+
  geom_violin(trim = FALSE, fill= "gray")+
  geom_boxplot()+
  coord_flip()+
  scale_y_continuous(trans = scales::pseudo_log_trans(base = 10))+
  geom_boxplot(width=0.25,
                        outlier.color = 'red',
                        colour = 'white',
                        fill='black') + coord_flip()+
  theme(axis.text.y = element_blank(),
                      axis.ticks.y = element_blank(),
                      axis.title.y = element_blank())+
annotate(geom = "text", size= 2.75,
         label= paste0("Upper Outlying Schools: ", upper0count),
         y = upperT+35,
         x=0.1, color="red",
         angle=0)+
  annotate(geom = "text", size= 2.75,
         label= paste0("Lower Outlying Schools: ", low0count),
         y = lowerT-3,
         x=0.1, color="red",
         angle=0)+
  geom_hline(yintercept = mn, color='darkgreen',
                         linetype="dotted")+
  annotate(geom = "text", size = 2.75, color = "darkgreen",
           fontface = "bold",
           label = paste0("Mean: ", round(mn)),
           x = 0.22,
           y = mn+1.75,
           angle = 90)+
  annotate(geom = "text", color = "lightskyblue", fontface= "bold",
           size = 2.75, fontface = "bold",
           label = paste0("Median: ", round(md)),
           x= 0,
           y = md-0.75,
           angle =90)+
  labs(title = "Distribution of Student-Teacher Ratios in MA",
       subtitle = "Violin plot with boxplot overlay and identfied outliers",
       x = "Student-Teacher Ratio",
       y = NULL,
       caption = "Source: U.S Department of Education"
  )+
  theme(plot.caption = element_text(hjust = 0),
        plot.subtitle = element_text(hjust = 0.5),
        plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.text = element_text(face = "bold"),
        axis.line.x = element_line(linewidth = 1),
        axis.line.y = element_blank()
        )
  sdt_tchrat_school
  
  saveRDS(sdt_tchrat_school, "sdt_tchrat_school.rds")
  
```
